title:            Flashlight Ministries
tagline:          From the rising of the sun unto the going down of the same the LORD'S name is to be praised (psalm 133:3).
canonical:        http://flmin.org

# Owner/author information
owner:
  name:           T. C. Howitt
  avatar:         todo
  bio:            "Director"
  email:          tc@flmin.org
  twitter:        thyflashlight
  facebook:       FlashlightMinistries
  github:         flashlightministries
  location:       "Union, OR"

business:
  name:           Flashlight Ministries

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

paginate: 5
paginate_path: "news/posts/:num"

JB:
  comments:
    provider: facebook
    disqus:
      short_name: jekyllbootstrap
    livefyre:
      site_id: 123
    intensedebate:
      account: 123abc
    facebook:
      appid: 1593142297566173
      num_posts: 5
      width: 100%
      colorscheme: light

  # Settings for sharing
  # Sharing is for things like tweet, plusone, hn upvotes, like, linkedin
  # Add a tweet button 		=> provider : tweet
  # Add a like button 		=> provider : like (you also need a facebook appid)
  # Add a plus one button 	=> provider : plusone
  # Add a HN button 		=> provider : hn
  # Add them all (i.e. hn + tweet + plusone + like) => provider : all
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : all
    twitter :
      size :
      via :
      count :
    facebook :
      appid : 1593142297566173
      layout : button_count
      font :
      faces : false
      width : 90

# Links to include in top navigation
# For external links add external: true
links:
  - title: News
    url: /news
  - title: Links
    url: /links
  - title: About
    url: /about
  - title: Contact
    url: /contact

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

gems: [jekyll-paginate, jekyll-watch]
